[build]
command = """
curl -sL https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz | tar xz && \
sed -i 's|base_url = "/"|base_url = "https://yudhister.me"|' config.toml && \
./zola build
"""
publish = "public"

[build.environment]
ZOLA_VERSION = "0.19.2"  # Use your desired Zola version